/* AUTO-GÉNÉRÉ par scripts/build-gesture-exports.mjs — ne pas éditer.
 * Source : extension/data/gestures.json
 * Vocabulaire (séquence -> action) exposé en global pour le content script. */
(function (root) {
  const OGC_VOCABULARY = {
    "L": "page.back",
    "R": "page.forward",
    "U": "scroll.up",
    "D": "scroll.down",
    "RU": "page.top",
    "RD": "page.bottom",
    "RDRD": "page.bottom",
    "LURDR": "site.home",
    "URUURRDLDDL": "search.web",
    "UURRDDLDD": "help.toggle",
    "DUURRDRD": "tab.new",
    "DUURRDR": "tab.new",
    "DUURDRD": "tab.new",
    "DUURRDRR": "tab.new",
    "URRDRD": "tab.next",
    "UURRDR": "tab.next",
    "UURRDRD": "tab.next",
    "UURDRD": "tab.next",
    "UURRDRR": "tab.next",
    "DDLLULU": "tab.prev",
    "UULLDLD": "tab.prev",
    "UULDLD": "tab.prev",
    "UULLDL": "tab.prev",
    "UULLDLL": "tab.prev",
    "DRULDR": "tab.close",
    "DLULLUURRDR": "tab.close",
    "DLLULLUURDR": "tab.close",
    "DLLULLUURRDR": "tab.close",
    "DDLLULLUURRDR": "tab.close",
    "UR": "window.maximize",
    "DL": "window.minimize",
    "DRDDLLLUURUR": "zoom.in",
    "LDLDDRRULUUL": "zoom.out",
    "LRULRD": "bookmarks.add",
    "RURRDR": "bookmarks.add",
    "RURDDR": "bookmarks.add",
    "RURDLDR": "bookmarks.add",
    "RURDR": "bookmarks.add",
    "RURDDRR": "bookmarks.add",
    "RURUDDRR": "bookmarks.add",
    "URUDDRR": "bookmarks.add",
    "DDRURUULL": "page.saveAs",
    "DDRRURULLL": "page.saveAs",
    "DDRRURULL": "page.saveAs",
    "DDRRURUUUL": "page.saveAs"
  };
  root.OGC_VOCABULARY = OGC_VOCABULARY;
})(typeof window !== "undefined" ? window : globalThis);
