// AUTO-GÉNÉRÉ par scripts/build-gesture-exports.mjs — ne pas éditer.
// Source : extension/data/gestures.json
#pragma once
#include <stdint.h>

struct OgcEntry { const char* seq; uint16_t action_id; };

static const OgcEntry OGC_VOCAB[] = {
    { "DDLLULLUURRDR", 12 },
    { "DLLULLUURRDR", 12 },
    { "DRDDLLLUURUR", 15 },
    { "LDLDDRRULUUL", 16 },
    { "DLLULLUURDR", 12 },
    { "DLULLUURRDR", 12 },
    { "URUURRDLDDL", 7 },
    { "DDRRURULLL", 18 },
    { "DDRRURUUUL", 18 },
    { "DDRRURULL", 18 },
    { "DDRURUULL", 18 },
    { "UURRDDLDD", 8 },
    { "DUURRDRD", 9 },
    { "DUURRDRR", 9 },
    { "RURUDDRR", 17 },
    { "DDLLULU", 11 },
    { "DDRRUUR", 21 },
    { "DUURDRD", 9 },
    { "DUURRDR", 9 },
    { "RURDDRR", 17 },
    { "RURDLDR", 17 },
    { "URUDDRR", 17 },
    { "UULLDLD", 11 },
    { "UULLDLL", 11 },
    { "UURRDRD", 10 },
    { "UURRDRR", 10 },
    { "DDRRUR", 21 },
    { "DDRUUR", 21 },
    { "DRRUUR", 21 },
    { "DRULDR", 12 },
    { "LRULRD", 17 },
    { "RURDDR", 17 },
    { "RURRDR", 17 },
    { "URRDRD", 10 },
    { "UULDLD", 11 },
    { "UULLDL", 11 },
    { "UURDRD", 10 },
    { "UURRDR", 10 },
    { "DDDLL", 5 },
    { "DDDRR", 5 },
    { "DDLLL", 5 },
    { "DDRRR", 5 },
    { "DDRUR", 21 },
    { "DRRUR", 21 },
    { "DRURR", 21 },
    { "DRUUR", 21 },
    { "LURDR", 6 },
    { "RURDR", 17 },
    { "UULLL", 4 },
    { "UURRR", 4 },
    { "UUULL", 4 },
    { "UUURR", 4 },
    { "DDDL", 5 },
    { "DDDR", 5 },
    { "DDLL", 5 },
    { "DDRR", 5 },
    { "DLLL", 5 },
    { "DRRR", 5 },
    { "DRUR", 21 },
    { "LLDD", 20 },
    { "LLUU", 20 },
    { "RRDD", 19 },
    { "ULLL", 4 },
    { "URRR", 4 },
    { "UULL", 4 },
    { "UURR", 4 },
    { "UUUL", 4 },
    { "UUUR", 4 },
    { "DDL", 5 },
    { "DDR", 5 },
    { "DLL", 5 },
    { "DRR", 5 },
    { "LDD", 20 },
    { "LLD", 20 },
    { "LLU", 20 },
    { "LUU", 20 },
    { "RDD", 19 },
    { "RRD", 19 },
    { "ULL", 4 },
    { "URR", 4 },
    { "UUL", 4 },
    { "UUR", 4 },
    { "DL", 14 },
    { "LD", 20 },
    { "LU", 20 },
    { "RD", 19 },
    { "UR", 13 },
    { "D", 3 },
    { "L", 0 },
    { "R", 1 },
    { "U", 2 },
};
static const uint32_t OGC_VOCAB_LEN = 91;

static const char* const OGC_ACTIONS[] = {
    "page.back",
    "page.forward",
    "scroll.up",
    "scroll.down",
    "page.top",
    "page.bottom",
    "site.home",
    "search.web",
    "help.toggle",
    "tab.new",
    "tab.next",
    "tab.prev",
    "tab.close",
    "window.maximize",
    "window.minimize",
    "zoom.in",
    "zoom.out",
    "bookmarks.add",
    "page.saveAs",
    "element.next",
    "element.prev",
    "element.activate",
};
static const char* const OGC_LABELS[] = {
    "Page précédente",
    "Page suivante",
    "Monter",
    "Descendre",
    "Haut de page",
    "Bas de page",
    "Accueil du site",
    "Rechercher sur internet",
    "Aide",
    "Nouvel onglet",
    "Onglet suivant",
    "Onglet précédent",
    "Fermer l'onglet",
    "Agrandir la fenêtre",
    "Réduire la fenêtre",
    "Zoomer",
    "Dézoomer",
    "Ajouter aux favoris",
    "Enregistrer sous…",
    "Élément suivant",
    "Élément précédent",
    "Valider",
};
static const uint32_t OGC_ACTIONS_LEN = 22;
